# Generated by Django 2.2.1 on 2019-05-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_student_delete_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='img/web-3219281_640.jpg', upload_to='img'),
        ),
    ]
